### ISSUE TITLE
Use github.com/linode/linodego to use Linode APIv4 and reduce code

### ISSUE THREAD

**Issue by displague** [linode/packer-builder-linode#2]
Hi @dradtke !

I've recently taken the community started terraform-provider to official status.  I would love to do the same with this project.

I think a first step would be to convert this project to one that consumes the linodego wrapper for the v4 API.

**Comment by dradtke** [comment]
@displague I just pushed a commit to the [apiv4 branch](https://github.com/dradtke/packer-builder-linode/tree/apiv4) that _almost_ gets it working. Unfortunately, the image seems to get cleaned up by Linode almost immediately, and my best guess is that we need to wait until the image is actually done before exiting.

Unfortunately, Linode's v4 API doesn't seem to have any concept of an image status, and the `ListNotifications()` call is completely [broken](https://github.com/linode/linodego/issues/67). Any thoughts about how to solve this?

**Comment by displague** [comment]
@dradtke Sorry about that, I'll address `ListNotifications`.

https://github.com/terraform-providers/terraform-provider-linode/blob/master/linode/resource_linode_image.go#L154-L186

Also notice that `Create` also verifies that the Image still exists when the Instance status has returned to normal.  This is because a failed image will be deleted and will no longer be accessible.

https://github.com/terraform-providers/terraform-provider-linode/blob/master/linode/resource_linode_image.go#L111-L124


( @akerl was the contributor behind that )

**Comment by displague** [comment]
@dradtke https://github.com/linode/linodego/releases/tag/v0.7.1 corrects the notifications bug you discovered.  

It's been merged for a while but I hadn't pushed any tags/releases since before Kubecon and holidays.
